services:
  postgres:
    container_name: postgres-sql-w-a-c
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whatsapp_clone
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - whatsapp-clone
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-sql-w-a-c
      KC_DB_URL_DATABASE: whatsapp_clone
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_LOG_LEVEL: INFO
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      - whatsapp-clone
    command: ["start-dev", "--health-enabled=true"]
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 15s
      retries: 10
      timeout: 10s
      start_period: 10s

networks:
  whatsapp-clone:
    driver: bridge

volumes:
  postgres:
    driver: local